-- Itens do cardapio impresso que faltavam no sistema + precos das bebidas importadas das NFC-e.
-- Pode rodar mais de uma vez (ignora o que ja existe pelo nome).
SET NAMES utf8mb4;
START TRANSACTION;
INSERT INTO rest_categorias (nome, ordem, ativa) SELECT 'Café da manhã',0,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_categorias WHERE LOWER(nome)='café da manhã');
INSERT INTO rest_categorias (nome, ordem, ativa) SELECT 'Fits',8,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_categorias WHERE LOWER(nome)='fits');
INSERT INTO rest_categorias (nome, ordem, ativa) SELECT 'Cervejas',10,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_categorias WHERE LOWER(nome)='cervejas');
INSERT INTO rest_categorias (nome, ordem, ativa) SELECT 'Drinks',11,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_categorias WHERE LOWER(nome)='drinks');
INSERT INTO rest_categorias (nome, ordem, ativa) SELECT 'Doces',12,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_categorias WHERE LOWER(nome)='doces');
INSERT INTO rest_categorias (nome, ordem, ativa) SELECT 'Feijoada',13,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_categorias WHERE LOWER(nome)='feijoada');
INSERT INTO rest_categorias (nome, ordem, ativa) SELECT 'Bebidas',99,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_categorias WHERE LOWER(nome)='bebidas');

INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='café da manhã' ORDER BY id LIMIT 1),'Café com leite',NULL,6,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Café com leite');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='café da manhã' ORDER BY id LIMIT 1),'Café sem leite',NULL,5,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Café sem leite');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='café da manhã' ORDER BY id LIMIT 1),'Vitamina whey + fruta',NULL,12,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Vitamina whey + fruta');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='lanches leves' ORDER BY id LIMIT 1),'Tapioca Simples','Massa de tapioca e manteiga',12,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Tapioca Simples');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='lanches leves' ORDER BY id LIMIT 1),'Tapioca de Carne de Sol com Queijo','Manteiga, carne de sol desfiada e queijo mussarela',19,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Tapioca de Carne de Sol com Queijo');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='lanches leves' ORDER BY id LIMIT 1),'Tapioca de Frango','Manteiga e frango desfiado',16,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Tapioca de Frango');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='lanches leves' ORDER BY id LIMIT 1),'Cuscuz Simples','Massa de cuscuz e manteiga',12,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Cuscuz Simples');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='lanches leves' ORDER BY id LIMIT 1),'Cuscuz de Carne de Sol com Queijo','Manteiga, carne de sol desfiada e queijo mussarela',19,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Cuscuz de Carne de Sol com Queijo');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='lanches leves' ORDER BY id LIMIT 1),'Cuscuz com Frango','Manteiga e frango desfiado',16,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Cuscuz com Frango');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='lanches leves' ORDER BY id LIMIT 1),'Crepioca de Frango','Massa de crepioca recheada com frango desfiado',16,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Crepioca de Frango');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='lanches leves' ORDER BY id LIMIT 1),'Ovo Mexido',NULL,8,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Ovo Mexido');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='fits' ORDER BY id LIMIT 1),'Sanduíche natural de frango',NULL,10,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Sanduíche natural de frango');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='fits' ORDER BY id LIMIT 1),'Salada de frutas',NULL,12,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Salada de frutas');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='fits' ORDER BY id LIMIT 1),'Barrinha de proteína BOLD','Preço sob consulta',0,'COZINHA',1,1,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Barrinha de proteína BOLD');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='bebidas' ORDER BY id LIMIT 1),'Água mineral',NULL,5,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Água mineral');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='bebidas' ORDER BY id LIMIT 1),'Água com gás',NULL,6,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Água com gás');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='bebidas' ORDER BY id LIMIT 1),'Refrigerante lata',NULL,7,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Refrigerante lata');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='bebidas' ORDER BY id LIMIT 1),'Suco de laranja',NULL,14,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Suco de laranja');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='bebidas' ORDER BY id LIMIT 1),'Suco natural','Consulte os sabores',12,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Suco natural');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='cervejas' ORDER BY id LIMIT 1),'Heineken 600ml',NULL,16,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Heineken 600ml');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='cervejas' ORDER BY id LIMIT 1),'Stella long neck',NULL,10,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Stella long neck');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='cervejas' ORDER BY id LIMIT 1),'Stella 600ml',NULL,16,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Stella 600ml');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='cervejas' ORDER BY id LIMIT 1),'Stella Gold 600ml',NULL,16,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Stella Gold 600ml');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='drinks' ORDER BY id LIMIT 1),'Caipirinha Tradicional','Gelo, limão, açúcar e cachaça',14,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Caipirinha Tradicional');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='drinks' ORDER BY id LIMIT 1),'Caipifruta','Consulte as frutas disponíveis. Gelo, açúcar e vodka',16,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Caipifruta');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='drinks' ORDER BY id LIMIT 1),'Gin Tropical','Dose de gin e Red Bull',22,'BAR',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Gin Tropical');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='doces' ORDER BY id LIMIT 1),'Brownie',NULL,8,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Brownie');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='doces' ORDER BY id LIMIT 1),'Picolés de frutas','Preço sob consulta',0,'COZINHA',1,1,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Picolés de frutas');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='petiscos' ORDER BY id LIMIT 1),'Camarão Alho e Óleo','300g de camarão frito no alho e óleo, acompanha vinagrete e farofa',65,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Camarão Alho e Óleo');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='petiscos' ORDER BY id LIMIT 1),'Calabresa Acebolada com Fritas','200g de calabresa frita acebolada e 200g de fritas',42,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Calabresa Acebolada com Fritas');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='petiscos' ORDER BY id LIMIT 1),'Macaxeira Frita','300g de macaxeira frita',30,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Macaxeira Frita');
INSERT INTO rest_itens_cardapio (categoria_id, nome, descricao, preco, praca, ativo, pausado, ordem) SELECT (SELECT id FROM rest_categorias WHERE LOWER(nome)='feijoada' ORDER BY id LIMIT 1),'Feijoada Completa','Aos domingos. 500g de feijoada, arroz branco, farofa, couve e laranja',45,'COZINHA',1,0,0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM rest_itens_cardapio WHERE nome='Feijoada Completa');

-- Itens genericos antigos, agora separados em Tapioca/Cuscuz no cardapio impresso (so desativa, nao apaga)
UPDATE rest_itens_cardapio SET ativo=0 WHERE nome IN ('Carne de sol com queijo','Frango');

-- Precos das bebidas importadas (so onde ainda esta em R$ 0 e pausado) e liberacao para venda
UPDATE rest_itens_cardapio SET preco=13, pausado=0 WHERE nome LIKE 'Yopro 250ml%' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=7, pausado=0 WHERE nome LIKE 'H2OH 500ml%' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=10, pausado=0 WHERE nome LIKE 'Gatorade 500ml%' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=7, pausado=0 WHERE nome LIKE 'Coca-Cola Lata%' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=7, pausado=0 WHERE nome LIKE 'Schweppes%' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=14, pausado=0 WHERE nome LIKE 'Monster 473ml%' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=15, pausado=0 WHERE nome LIKE 'Red Bull 250ml%' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=6, pausado=0 WHERE nome LIKE 'Água Viena%' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=6, pausado=0 WHERE nome LIKE 'Água Mar Doce%' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=10, pausado=0 WHERE nome LIKE 'Cerveja Corona%' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=10, pausado=0 WHERE nome LIKE 'Cerveja Heineken 330ml' AND preco=0 AND pausado=1;
UPDATE rest_itens_cardapio SET preco=10, pausado=0 WHERE nome LIKE 'Cerveja Stella Artois Pure Gold 330ml' AND preco=0 AND pausado=1;
COMMIT;